#cloud-config

# upgrade existing packages and install httpd
package_update: true
package_upgrade: true
packages:
  - httpd

# create a simple HTML page and store it in /var/www/html/index.html
write_files:
  - path: /var/www/html/index.html
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Welcome to My Website</title>
      </head>
      <body>
          <h1>Hello, World!</h1>
          <p>This is a custom HTML page served from my Apache server on EC2.</p>
      </body>
      </html>
    owner: root:root
    permissions: '0644'

# run the following commands
runcmd:
  - systemctl start httpd.service
  - systemctl enable httpd.service
  - systemctl restart httpd.service
